services:
  postgres_test:
    image: postgres:16.8
    container_name: postgres_test_container
    environment:
      POSTGRES_USER: test_user
      POSTGRES_PASSWORD: test_pass
      POSTGRES_DB: test_db
    ports:
      - '5433:5432'
    volumes:
      - pgdata_test:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U test_user']
      interval: 2s
      timeout: 5s
      retries: 10

volumes:
  pgdata_test:
